"""Build the '## Self-test' section appended to each revision doc.

Replaces the hand-written SR cards deleted on 2026-09-06. Two reasons they went:

  * 368 cards were written, 3 were ever scheduled for review — 0.8% adoption.
  * Being hand-written, they were a FOURTH copy of every fact and drifted from
    the notes. The 2026-09-06 currency sweep fixed 58 facts in the notes; every
    card kept asserting the old ones.

So this generator takes nothing on faith and invents nothing: every answer is
lifted VERBATIM from the revision body the reader has just finished, which is
itself lifted verbatim from the note. It cannot disagree with the note.

It also drills the right thing. The measured failure mode is DISCRIMINATION —
answers marked 'sure' and wrong, where the fact was known but the wrong one of
two neighbours was retrieved. A definition card ("what is X?") does not test
that. A comparison table with the cells blanked does: you must produce both
sides and the axis that separates them.
"""
import re

def _tables(md):
    """(caption, header_line, sep_line, [body_rows]) for each comparison table.

    A comparison table has >=3 columns and >=2 body rows — a 2-column table is
    a glossary, not a discrimination.
    """
    out, lines = [], md.splitlines()
    i = 0
    while i < len(lines):
        if lines[i].startswith('|') and i + 1 < len(lines) and re.match(r'^\|[\s:|-]+\|$', lines[i+1]):
            hdr, sep, j = lines[i], lines[i+1], i + 2
            rows = []
            while j < len(lines) and lines[j].startswith('|'):
                rows.append(lines[j]); j += 1
            if hdr.count('|') >= 4 and len(rows) >= 2:
                cap = ''
                for k in range(i - 1, max(-1, i - 4), -1):     # nearest heading above
                    if lines[k].startswith('#'):
                        cap = lines[k].lstrip('# ').strip(); break
                out.append((cap, hdr, sep, rows))
            i = j
        else:
            i += 1
    return out

def _blank(row):
    """Keep the row label, blank every other cell."""
    cells = row.split('|')
    inner = cells[1:-1] if row.rstrip().endswith('|') else cells[1:]
    return '| ' + inner[0].strip() + ' |' + '|'.join('   ' for _ in inner[1:]) + '|'

def _traps(md):
    """(title, body-lines) for each trap callout, verbatim."""
    out, cur, buf = [], None, []
    for line in md.splitlines():
        m = re.match(r'^>\s*\[!warning\]-?\s*(?:Trap\s*[—:-]\s*)?(.+?)\s*$', line)
        if m:
            if cur: out.append((cur, buf))
            cur, buf = m.group(1), []
        elif cur is not None and line.startswith('>'):
            buf.append(line)
        elif cur is not None:
            out.append((cur, buf)); cur, buf = None, []
    if cur: out.append((cur, buf))
    return [(t, b) for t, b in out if b]

def section(body, note):
    """The '## Self-test' markdown, or None if the note yields nothing to drill."""
    tabs, traps = _tables(body), _traps(body)
    if not tabs and not traps:
        return None

    out = ['## Self-test',
           '',
           '> [!question] Close the doc first.',
           '> Reading a comparison and being able to *produce* it are different skills, and',
           '> only the second one survives a question written to make two answers look alike.',
           '> Say each answer out loud before you unfold it — if you can only recognise it,',
           '> you do not know it yet.',
           '']

    n = 0
    for cap, hdr, sep, rows in tabs:
        n += 1
        out.append(f'**{n}. {cap or "Fill in the grid"}** — fill the blank cells from memory.')
        out += ['', hdr, sep] + [_blank(r) for r in rows] + ['']
        out.append('> [!success]- Answer')
        out += [f'> {l}' for l in [hdr, sep] + rows]
        out.append('')

    if traps:
        out += ['### The traps', '',
                '*Each of these is a place a plausible-looking answer is wrong. Say why before unfolding.*', '']
        for title, blines in traps:
            out.append(f'> [!question]- {title}')
            out += [('> ' + l.lstrip('>').strip()).rstrip() for l in blines]
            out.append('')

    out.append(f'*Answers are lifted verbatim from [[{note}]]. '
               'Generated by `_scripts/build_revision.py` — do not edit.*')
    return '\n'.join(out).rstrip()
